var englishDB = {
    topicTitles: {
        topic1: "Topic 1: Greetings & Basics",
        topic2: "Topic 2: To Be & Present Simple",
        topic3: "Topic 3: Countable & Uncountable"
    },

    topic1: [
        { word: "Hello / Hi", trans: "Привет (формальное / неформальное приветствие)." },
        { word: "Good morning", trans: "Доброе утро." },
        { word: "Good afternoon", trans: "Добрый день." },
        { word: "Good evening", trans: "Добрый вечер." },
        { word: "Goodbye / Bye", trans: "До свидания / Пока." },
        { word: "See you later", trans: "Увидимся позже." },
        { word: "How are you?", trans: "Как дела?" },
        { word: "I'm fine, thanks", trans: "У меня всё хорошо, спасибо." },
        { word: "What's your name?", trans: "Как тебя зовут?" },
        { word: "My name is...", trans: "Меня зовут..." },
        { word: "Nice to meet you", trans: "Приятно познакомиться." },
        { word: "Thank you / Thanks", trans: "Спасибо." },
        { word: "You're welcome", trans: "Пожалуйста (в ответ на благодарность)." },
        { word: "Please", trans: "Пожалуйста (при просьбе)." },
        { word: "Sorry / Excuse me", trans: "Извини / Простите (за беспокойство)." },
        { word: "Yes / No", trans: "Да / Нет." },
        { word: "Maybe", trans: "Может быть." },
        { word: "I don't understand", trans: "Я не понимаю." },
        { word: "Can you repeat, please?", trans: "Можете повторить, пожалуйста?" },
        { word: "How do you say ... in English?", trans: "Как сказать ... по-английски?" }
    ],

    topic2: [
        { word: "I am (I'm)", trans: "Я есть / являюсь. I'm a student." },
        { word: "You are (You're)", trans: "Ты есть / вы есть. You're right." },
        { word: "He is (He's)", trans: "Он есть. He's tall." },
        { word: "She is (She's)", trans: "Она есть. She's smart." },
        { word: "It is (It's)", trans: "Это есть (о предметах/животных). It's a cat." },
        { word: "We are (We're)", trans: "Мы есть. We're friends." },
        { word: "They are (They're)", trans: "Они есть. They're here." },
        { word: "am not / isn't / aren't", trans: "Отрицание глагола to be: I'm not, he isn't, they aren't." },
        { word: "Am I...? / Is he...? / Are you...?", trans: "Вопросительная форма: инверсия подлежащего и to be." },
        { word: "Present Simple", trans: "Настоящее простое время: регулярные действия, факты, расписания." },
        { word: "I / you / we / they + V", trans: "Глагол в начальной форме: I work, they play." },
        { word: "he / she / it + V-s", trans: "Глагол с окончанием -s/-es: he works, she goes." },
        { word: "do / does", trans: "Вспомогательный глагол для вопросов и отрицаний: Do you like? Does he know?" },
        { word: "don't / doesn't", trans: "Отрицание: I don't like, he doesn't know." },
        { word: "always / usually / often", trans: "Маркеры Present Simple: всегда, обычно, часто." },
        { word: "sometimes / rarely / never", trans: "Иногда, редко, никогда." },
        { word: "every day / every week", trans: "Каждый день / каждую неделю." },
        { word: "on Mondays / in the morning", trans: "По понедельникам / утром." },
        { word: "like / love / hate", trans: "Глаголы предпочтений: I like coffee, she hates rain." },
        { word: "want / need / have", trans: "Хотеть, нуждаться, иметь: I want tea, he has a car." }
    ],

    topic3: [
        // Исчисляемые существительные
        { word: "Countable nouns", trans: "Исчисляемые существительные: можно посчитать (one carrot, two carrots). Имеют форму множественного числа." },
        { word: "carrot", trans: "морковь — исчисляемое." },
        { word: "apricot", trans: "абрикос — исчисляемое." },
        { word: "melon", trans: "дыня — исчисляемое." },
        { word: "cucumber", trans: "огурец — исчисляемое." },
        { word: "lemon", trans: "лимон — исчисляемое." },

        // Неисчисляемые существительные
        { word: "Uncountable nouns", trans: "Неисчисляемые существительные: нельзя посчитать поштучно. Всегда в единственном числе, с глаголом is." },
        { word: "wine", trans: "вино — неисчисляемое (жидкость)." },
        { word: "lemonade", trans: "лимонад — неисчисляемое (жидкость)." },
        { word: "vegetable oil", trans: "растительное масло — неисчисляемое." },
        { word: "vinegar", trans: "уксус — неисчисляемое." },
        { word: "cocoa", trans: "какао — неисчисляемое." },
        { word: "soda", trans: "газировка — неисчисляемое." },
        { word: "food", trans: "еда — неисчисляемое." },
        { word: "ham", trans: "ветчина — неисчисляемое." },
        { word: "fish", trans: "рыба — неисчисляемое (как еда)." },
        { word: "pasta", trans: "паста — неисчисляемое." },
        { word: "fruit", trans: "фрукты — неисчисляемое (в общем смысле)." },
        { word: "flour", trans: "мука — неисчисляемое." },
        { word: "butter", trans: "масло (сливочное) — неисчисляемое." },
        { word: "meat", trans: "мясо — неисчисляемое." },
        { word: "bread", trans: "хлеб — неисчисляемое." },
        { word: "cheese", trans: "сыр — неисчисляемое." },
        { word: "salt", trans: "соль — неисчисляемое." },
        { word: "mushroom", trans: "грибы — неисчисляемое (как масса)." },
        { word: "pepper", trans: "перец — неисчисляемое." },
        { word: "honey", trans: "мёд — неисчисляемое." },
        { word: "sugar", trans: "сахар — неисчисляемое." },
        { word: "rice", trans: "рис — неисчисляемое (крупа)." },
        { word: "porridge", trans: "овсяная каша — неисчисляемое." },
        { word: "buckwheat", trans: "гречка — неисчисляемое." },
        { word: "oatmeal", trans: "овёс / овсянка — неисчисляемое." },
        { word: "semolina", trans: "манка — неисчисляемое." },
        { word: "pearl-barley", trans: "перловка — неисчисляемое." },
        { word: "barley", trans: "ячмень — неисчисляемое." },
        { word: "lentil", trans: "чечевица — неисчисляемое." },
        { word: "green pea", trans: "зелёный горошек — неисчисляемое." },
        { word: "wheat", trans: "пшено / пшеница — неисчисляемое." },

        // Способы счёта неисчисляемых
        { word: "a bar of chocolate", trans: "плитка шоколада." },
        { word: "a bar of soap", trans: "кусок мыла." },
        { word: "a chunk of", trans: "большой кусок чего-либо." },
        { word: "a bottle of water", trans: "бутылка воды." },
        { word: "a bowl of soup", trans: "миска супа." },
        { word: "a plate of meat", trans: "порция мяса." },
        { word: "a slice of bread", trans: "ломтик хлеба." },
        { word: "a carton of milk", trans: "упаковка молока." },
        { word: "a bag of chips", trans: "пачка чипсов." },
        { word: "a packet of", trans: "пачка / упаковка чего-либо." },
        { word: "a bucket of", trans: "ведро чего-либо." },
        { word: "a crate of", trans: "ящик чего-либо." },
        { word: "a drop of", trans: "капля чего-либо." },
        { word: "a bunch of", trans: "гроздь / букет чего-либо." },
        { word: "a cup of coffee", trans: "чашка кофе." },
        { word: "a game of chess", trans: "партия в шахматы." },
        { word: "a glass of wine", trans: "бокал вина." },
        { word: "a jar of jam", trans: "банка варенья." },
        { word: "a jug of lemonade", trans: "кувшин лимонада." },
        { word: "a can of cola", trans: "банка колы." },
        { word: "a tin", trans: "консервная банка." },
        { word: "a loaf of bread", trans: "буханка хлеба." },
        { word: "a piece of cheese", trans: "кусок сыра." },
        { word: "a sheet of paper", trans: "лист бумаги." },
        { word: "a kilo of meat", trans: "килограмм мяса." },
        { word: "a litre of water", trans: "литр воды." },

        // much / many / little / few / some / any
        { word: "much / little", trans: "определяют НЕисчисляемые существительные: much snow, little sugar." },
        { word: "many / few", trans: "определяют исчисляемые существительные: many spoons, few knives." },
        { word: "a little", trans: "немного (позитивный оттенок): I have a little time — у меня есть немного времени." },
        { word: "little", trans: "мало, недостаточно (негативный оттенок): I have little time — у меня мало времени." },
        { word: "a few", trans: "несколько (позитивный оттенок): He has a few friends — у него есть несколько друзей." },
        { word: "few", trans: "мало, почти нет (негативный оттенок): He has few friends — у него мало друзей." },
        { word: "a lot of / lots of", trans: "много — используется и с исчисляемыми, и с неисчисляемыми: a lot of friends, a lot of snow." },
        { word: "some", trans: "несколько / какой-то — в утвердительных предложениях и вопросах-предложениях: There are some coins." },
        { word: "any", trans: "сколько-нибудь / никакой — в вопросительных и отрицательных предложениях: I don't have any coins." },

        // Упражнение 1: a few / few / a lot of (пропуски)
        { word: "Let us take ___ friends with us. (несколько)", trans: "a few — Let us take a few friends with us." },
        { word: "There are ___ fruit-trees in our garden. (много)", trans: "a lot of — There are a lot of fruit-trees in our garden." },
        { word: "We have very ___ copy-books at home. (мало)", trans: "few — We have very few copy-books at home." },
        { word: "My sister has ___ books. (много)", trans: "a lot of — My sister has a lot of books." },
        { word: "Let us take ___ of them. (несколько)", trans: "a few — Let us take a few of them." },
        { word: "Our children have very ___ lessons today. (мало)", trans: "few — Our children have very few lessons today." },
        { word: "She always makes ___ mistakes in her letters. (много)", trans: "a lot of — She always makes a lot of mistakes in her letters." },
        { word: "We have very ___ towers in London. (мало)", trans: "few — We have very few towers in London." },
        { word: "There are ___ new words in the text. (несколько)", trans: "a few — There are a few new words in the text." },

        // Упражнение 3: Choose the right word
        { word: "I can't see ___ chalk at the blackboard. (any/some)", trans: "any — chalk неисчисляемое, отрицательное предложение." },
        { word: "There ___ no glue in the bottle. (is/are)", trans: "is — glue неисчисляемое." },
        { word: "This ___ pencil case and these ___ pens. (is/are)", trans: "is / are — this + ед.ч., these + мн.ч." },
        { word: "There are ___ pencils in the pencil case. (few/little)", trans: "few — pencils исчисляемое." },
        { word: "There was ___ paper in the backpack yesterday. (few/little)", trans: "little — paper неисчисляемое." },
        { word: "The spectacles ___ on the shelf. (is/are)", trans: "are — spectacles всегда во множественном числе." },
        { word: "There are not ___ students in this college. (much/many/any)", trans: "many — students исчисляемое; или any в отрицании." },
        { word: "The pair of socks ___ behind the bed. (was/were)", trans: "was — подлежащее 'the pair' (ед.ч.)." },

        // Перевод RU → EN
        { word: "У меня есть много друзей.", trans: "I have many friends. / I have a lot of friends." },
        { word: "На улице много снега.", trans: "There is much snow in the street. / There is a lot of snow in the street." },
        { word: "На дереве сидит несколько птиц.", trans: "There are a few birds in the tree." },
        { word: "У меня мало денег.", trans: "I have little money. / I have a little money." },
        { word: "У вас есть какие-либо вопросы?", trans: "Do you have any questions?" },
        { word: "В этой книге мало упражнений.", trans: "There are few exercises in this book." },
        { word: "Я не пью много кофе.", trans: "I don't drink much coffee." },
        { word: "Я вижу много полезных книг на этой полке.", trans: "I see many useful books on this shelf." },
        { word: "В моем чае много молока.", trans: "There is much milk in my tea. / There is a lot of milk in my tea." },
        { word: "Как много у тебя друзей?", trans: "How many friends do you have?" },
        { word: "Сколько сахара у тебя есть?", trans: "How much sugar do you have?" },

        // Скороговорка (бонус)
        { word: "If two witches were watching two watches, which witch would watch which watch?", trans: "Если две ведьмы смотрели бы на двое часов, то какая ведьма смотрела бы на какие часы? (скороговорка на отработку [w] и [tʃ])" }
    ]
};
